=== Bawrip/FactsWithBracketParser/src/test/resources/xml/ModelSchema.1.0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns="http://www.amazanov.com/model/XMLschema" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.amazanov.com/model/XMLschema" elementFormDefault="qualified">
	<xs:complexType name="And">
		<xs:sequence>
			<xs:choice minOccurs="2" maxOccurs="unbounded">
				<xs:element name="Fact" type="Fact"/>
				<xs:element name="And" type="And"/>
				<xs:element name="Or" type="Or"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Or">
		<xs:sequence>
			<xs:choice minOccurs="2" maxOccurs="unbounded">
				<xs:element name="Fact" type="Fact"/>
				<xs:element name="And" type="And"/>
				<xs:element name="Or" type="Or"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Fact">
		<xs:attribute name="value" type="FactPattern"/>
	</xs:complexType>
	
	<xs:complexType name="Rule">
		<xs:sequence>
			<xs:choice minOccurs="1" maxOccurs="1">
				<xs:element name="And" type="And"/>
				<xs:element name="Or" type="Or"/>
				<xs:element name="Fact" type="Fact"/>
			</xs:choice>
			<xs:element name="ResultFact" type="FactPattern"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Rules">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="Rule" type="Rule"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Model">
		<xs:sequence>
			<xs:element name="Rules" type="Rules" minOccurs="1" maxOccurs="1"/>
			<xs:element name="KnownFacts" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Fact" type="FactPattern" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:simpleType name="FactPattern">
		<xs:restriction base="xs:string">
			<xs:pattern value="_*[a-zA-Z]+[a-zA-Z0-9_]*"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:element name="Model" type="Model"/>
	
</xs:schema>

=== Bawrip/FactsWithBracketParser/src/test/resources/xml/negative8.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Model xmlns="http://www.amazanov.com/model/XMLschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.amazanov.com/model/XMLschema ModelSchema.1.0.xsd">    <Rules>
        <Rule>
            <Or>
                <And>
                    <Fact value="M"/>
                    <Fact value="E"/>
                </And>
                <And>
                    <Fact value="Y"/>
                    <Fact value="T"/>
                </And>
            </Or>
            <ResultFact>F</ResultFact>
            <!--Second expression element-->
            <And>
                <Or>
                    <Fact value="T"/>
                    <Fact value="U"/>
                </Or>
                <Fact value="P"/>
            </And>
            <ResultFact>R</ResultFact>
        </Rule>
    </Rules>
    <KnownFacts>
        <Fact>A</Fact>
        <Fact>B</Fact>
        <Fact>C</Fact>
        <Fact>D</Fact>
    </KnownFacts>
</Model>

=== Bawrip/FactsWithBracketParser/src/test/resources/xml/negative7.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Model xmlns="http://www.amazanov.com/model/XMLschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.amazanov.com/model/XMLschema ModelSchema.1.0.xsd">    <Rules>
        <Rule>
            <Or>
                <And>
                    <Fact value="M"/>
                    <Fact value="E"/>
                </And>
                <And>
                    <Fact value="Y"/>
                    <Fact value="T"/>
                </And>
            </Or>
            <ResultFact>F</ResultFact>
        </Rule>
    </Rules>
    <KnownFacts>
        <Fact><!-- Empty 'Fact' element--></Fact>
    </KnownFacts>
</Model>
